a = int(input("Enter a number 1:"))
b = int(input("Enter a number 2:"))
print("The Sum of the Two Numbers is: ",a+b)
print("The difference of the two numbers is: ",a-b)
print("The product of the two numbers is: ",a*b)
print("The division of the two numbers is: ",a/b)
print("The modulus of the two numbers is: ",a%b)
print("The exponent of the two numbers is: ",a**b)
print("The floor division of the two numbers is: ",a//b)
